apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pastely-frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: pastely
        tier: frontend
    spec:
      containers:
        - name: pastely-frontend
          image: gcr.io/pastely-1357/pastely-frontend:d702bac8b9edee3dd48148370bdefd23d8fd4ccc.production.v1
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
