apiVersion: v1
kind: Service
metadata:
  name: pastely-frontend
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  selector:
    app: pastely
    tier: frontend
