node {
    stage 'checkout'
    git 'https://github.com/dewyatt/pastely-frontend.git'

    stage 'testing'
    sh './deploy/test.sh'

    stage 'build-staging'
    sh 'git rev-parse HEAD | head -c 40 > GIT_COMMIT'
    git_sha1=readFile('GIT_COMMIT')
    sh "./deploy/build.sh staging $git_sha1 pastely-staging.dewyatt.com"

    stage 'deploy-staging'
    sh "./deploy/deploy.sh staging $git_sha1"

    deploy_prod=input message: 'Deployed to staging. Do you want to deploy to production?'
    stage 'build-production'
    sh "./deploy/build.sh production $git_sha1 pastely.dewyatt.com"

    stage 'deploy-production'
    sh "./deploy/deploy.sh production $git_sha1"
}
